//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMove.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSMove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag+4qUaJ3IuE6xBqIzcFpf64IsWskXzwWOW27ki0E9hgfENiopCUDBoDvgNacHtXXqvb+0osddCVZ+RSbrAnrHJMLZ+on5TKg863N2pq+CnuqxKqNpJ9r1BZvOvi03MiOcsm25mQxEHPoI3h70KowhD4ysCAOy9HDfG9KO1fpiTuJDjqJsowsr1adJMwcsIe2YoRhiWb83K6oTmjfsR057fC27eVa6U9aizm+eMTRYSspQr6BP1c0NhfNlkKlrf0VVsu20lsk6ab4ilDRI7KyLyiM7CCIIb3C3gGDhiy+ukJ7MnVA0iDsRy/+RMnGIU5BL2zbKAO232wW38GnqXnjUpNALWyR+DMJq97NsO3Dnkw5wBTvlwx/7AKfsbDZHmqbhpjz7sH4wY/pZfsqLgHo/HGswIMXGLQqCZh0e8oW9ZwGUzD//NV1AJIu7J7risQKMgIdvU7I/Ts59FQmt59zBzwfw66k1ICU6w9Mr/rwi+Xbu0binN4P7TlpKHSGn0T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperBase64String {
            get {
                return ResourceManager.GetString("WrapperBase64String", resourceCulture);
            }
        }
    }
}
