openapi: 3.0.3
info:
  version: '20210512'
  title: PullPosNumber
  description: 'Interfejs do do inicjalizowania stanowiska POS w MOK.'
paths: 
    /rest/dkz029/channel/posNumber/{ComputerName}:
      get:
        description: 'Ustawienie na podstawie zadanej nazwy komputera ciasteczka z nazwa komputera celem dalszego wykorzystania przez js, userLogin ma zwrocic dodatkowo dane terminala, drukarki, posu. W logice biznesowej loginu zawrzec ograniczenia, aby computerName bylo tylko z naszego slownika przypietego do uzytkownika / pos / mok, a nie dowolne / walidacja'
        parameters:
          - $ref: '#/components/parameters/ComputerName'
        responses:
          302:
            description: OK, redirect do strony glownej crm-a celem zaladowania js 
            headers:  
              Set-Cookie:
                $ref: '#/components/headers/Set-Cookie' 
          400:
            description: bad request 
            content:
              text/html:
                schema:
                  type: string
                  default : '<html><head><title>e-Toll: Coś poszło nie tak, skontaktuj się z administratorem aplikacji</title><head><body>Coś poszło nie tak, skontaktuj się z administratorem aplikacji.</br>Komunikat techniczny: Bad request</body></html>'                    
          401:
            description: unauthorized
            content:
              text/html:
                schema:
                  type: string
                  default : '<html><head><title>e-Toll: Nie udało się zalogować do stanowiska</title><head><body>Nie udało się zalogować do stanowiska.</br>Wciśnij F5 by odświeżyć stronę lub zamknij i ponownie uruchom przeglądarkę.</br>Prawdopodobnie wprowadzono nieprawidłowe poświadczenia.</body></html>'                   
          500: 
            description: unhandled exception
            content:
              text/html:
                schema:
                  type: string
                  default: '<html><head><title>e-Toll: Coś poszło nie tak, skontaktuj się z administratorem aplikacji</title><head><body>Coś poszło nie tak, skontaktuj się z administratorem aplikacji.</br>Komunikat techniczny: Internal server error</body></html>'                  
components:
  parameters:
    ComputerName:
      name: ComputerName
      in: path
      required: true
      schema:
        type: string
        format: string15
        minLength: 1
        maxLength: 15
  headers:
    Set-Cookie:
      description: Session cookie
      required: true
      schema: 
        type: string
        format: string1024
        minLength: 1
        maxLength: 1024
        default : 'PosNumber=a3fWadsd33; Expires=Wed, 21 Oct 2015 07:28:00 GMT'