//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAEFMetadataType.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int IdAdres { get; set; }
        public int IdKlient { get; set; }
        public string Ulica { get; set; }
        public string NumerBudynku { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
