//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tkomp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tkomp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test połączenia.
        /// </summary>
        public static string MainView_ConnectionTest {
            get {
                return ResourceManager.GetString("MainView_ConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załaduj dane.
        /// </summary>
        public static string MainView_LoadData {
            get {
                return ResourceManager.GetString("MainView_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string MainView_Login {
            get {
                return ResourceManager.GetString("MainView_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string MainView_Password {
            get {
                return ResourceManager.GetString("MainView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie z serwerem &apos;{0}&apos; się nie powiodło..
        /// </summary>
        public static string MainViewModel_Msg_ConnectionFailed {
            get {
                return ResourceManager.GetString("MainViewModel_Msg_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączenie z serwerem &apos;{0}&apos; się powiodło..
        /// </summary>
        public static string MainViewModel_Msg_ConnectionSucces {
            get {
                return ResourceManager.GetString("MainViewModel_Msg_ConnectionSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ===============================================================
        ///-- Server version 10
        ///-- Standardowy skrypt, który zwraca normalną ilość informacji
        ///-- o schematach kolumn.
        ///-- ===============================================================
        ///--DECLARE @ObjectSchema1 NVARCHAR(128) = N&apos;dbo&apos;
        ///--DECLARE @ObjectSchema2 NVARCHAR(128) = N&apos;dbo&apos;
        ///--DECLARE @ObjectSchema3 NVARCHAR(128) = N&apos;dbo&apos;
        ///--DECLARE @ObjectName1 NVARCHAR(128)   = N&apos;Table_A&apos;
        ///--DECLARE @ObjectName2 NVARCHAR(128)   = N&apos;Table_B&apos;
        ///--DECLARE @Ob [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSSQL_GetTablesColumnsV10 {
            get {
                return ResourceManager.GetString("MSSQL_GetTablesColumnsV10", resourceCulture);
            }
        }
    }
}
